### ISSUE TITLE
Pkg.build("GR") fails because of a curl fetching process

### ISSUE THREAD

**Issue by ijneb** [jheinen/GR.jl#108]
`LoadError: failed process: Process('curl -L -f -o downloads/gr-0.30.2-Linux-i686.tar.gz https://gr-framework.org/downloads/gr-0.30.2-Linux-i686.tar.gz', ProcessExited(22)) [22]`

After trying to run the curl command to see what happens, it returns `curl: (22) The requested URL returned error: 404 not found`.

The tar isn't in `https://gr-framework.org/downloads/`.

**Comment by FlorianRhiem** [comment]
We do not provide pre-built binaries of the GR runtime for 32bit linux systems. To use GR, please build and install the runtime manually, using the sources from: https://github.com/sciapp/gr
If you install it in `/usr/local/gr`, `/opt/gr` or `~/gr`, the runtime will automatically be found by the [GR.jl install script](https://github.com/jheinen/GR.jl/blob/master/deps/build.jl), otherwise you need to set the `GRDIR` environment variable to the path of the runtime.

**Comment by ijneb** [comment]
Alrighty! Thanks
