### ISSUE TITLE
Plotting 8000 element array causes GKSTerm exit

### ISSUE THREAD

**Issue by accopeland** [jheinen/GR.jl#144]
MWE:
```
julia> r=rand(8000)
julia> using Plots
julia> plot(r)
```

I'm running Julia 1.0.0 [5d4eaca0c9] ,   [28b8d3ca] GR v0.32.3,   [91a5bcdd] Plots v0.20.1 .  
When I attempt to plotting an array (Array{Float64,1}) of 8000 or more elements  GKSTerm displays the plot then immediately exits. I have not been able to determine a minimum size which reproduces the error consistently, but on my machine (2.9GHz Core i7 8GB OSX 10.11.6) the problem begins somewhere after 6200 elements. 

I have observed the same behavior if instead I attempt the plot using GR directly:
```
julia> using GR
julia> GR.plot(r)
```

Even with the 8000 element array memory use during rendering doesn't seem excessive, though it is quite slow.

Any ideas what might be going on?

**Comment by jheinen** [comment]
I can't reproduce the problem, even not with ~100000 points.
Could you please download the latest run-time and try again?

```julia
ENV["GRDIR"]=""
] build
```

I am on `"0.32.0.post5"`.

```julia
using GR
version()
```

**Comment by accopeland** [comment]
```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```
First, report on existing setup, then remove it and update
```
julia> ENV["GRDIR"]
"/Users/copeland/.julia/packages/GR/OAtrI/src/../deps/gr"

julia> ENV["GRDIR"]=""

(v1.0) pkg> rm GR
  Updating `~/.julia/environments/v1.0/Project.toml`
  [28b8d3ca] - GR v0.32.3
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]

(v1.0) pkg> add GR
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [28b8d3ca] + GR v0.32.3
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]
```
Interesting that GR version is reported as 0.32.3 
```
(v1.0) pkg> build
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/KvXoO/deps/build.log`
  Building Arpack ──────────→ `~/.julia/packages/Arpack/WP3ru/deps/build.log`
  Building Conda ───────────→ `~/.julia/packages/Conda/m7vem/deps/build.log`
  Building PyCall ──────────→ `~/.julia/packages/PyCall/akNFy/deps/build.log`
  Building Rmath ───────────→ `~/.julia/packages/Rmath/Py9gH/deps/build.log`
  Building CodecZlib ───────→ `~/.julia/packages/CodecZlib/wwgbh/deps/build.log`
  Building GR ──────────────→ `~/.julia/packages/GR/fnyt8/deps/build.log`
  Building FFTW ────────────→ `~/.julia/packages/FFTW/p7sLQ/deps/build.log`
  Building Plots ───────────→ `~/.julia/packages/Plots/MnXMC/deps/build.log`

julia> using GR

julia> version()
"0.32.0"
```
Very surprised to see version 0.32.0 now after the update. I tried the test from the GR docs and also the plot command I am having trouble with.
```
julia> histogram(rand(10000)
julia> plot(rand(10000))
```
histogram works, but the plot command opens a window which immediately closes as before. Maybe not so strange since the version does not appear to have been changed despite the update.

**Comment by mokus0** [comment]
same issue here.  This started very recently (just today).  I have been using GR extensively and suddenly it's almost 100% unable to do anything at all that I throw at it.  Tried rebuilding, and also tried nuking my entire ~/.julia and reinstalling everything.  Cannot use plot() with more than about 5000 points.

GR.version() here is 0.35.0

**Comment by jheinen** [comment]
I can reproduce that behaviour and we'll try to find out what the reason is. Sorry for that.

In the meantime, you can use the Qt terminal for output (`export GKS_WSTYPE=gksqt`). I'm not sure whether it is a rendering problem related to a macOS update or whether there is some inter-process communication problem.

**Comment by mokus0** [comment]
Thinking back to recent system changes, the most suspicious one I can think of is the new XCode update, which I installed sometime in the last few days.  I'm not 100% sure but it very well could have been yesterday.

**Comment by jheinen** [comment]
Could you please try to use [this](https://gr-framework.org/downloads/GKSterm.tar.gz) GKSTerm.app version? The problem seems to be related to the build system. Simply replace the `GKSTerm.app` in your GR installation with the contents of this tar file - the subpath is `deps/gr/Applications`.

**Comment by accopeland** [comment]
The GKSTerm.app from the linked tarball (installed
to ~/.julia/packages/GR/k8wwU/deps/gr/Applications)  seems to work.

GR.plot(rand(10000))

plots correctly without exiting.  Thanks. I'd love to know what the issue
was if you've sorted it out.

**Comment by FlorianRhiem** [comment]
We currently use macOS 10.9 for building the GR runtime in our CI system, to make sure that we don't lose downwards compatibility with old macOS versions. It turns out that there is something broken in terms of upwards compatibility in connection to laptop screens (likely in connection with retina displays). The 10.9-built GKSTerm works fine when using macOS 10.14 and a thunderbolt display, but fails reliably as soon as I switch to the built-in retina screen. A 10.14-built GKSTerm like the one in the tarball works fine in both cases. So far I was unable to pinpoint what exactly is causing this behavior.

We will need to rethink our CI system for macOS, for example by updating the build machine to 10.14 and relying on the macOS deployment target setting to keep downwards compatibility, or by making the GKSTerm.app dependent on the macOS version.

**Comment by accopeland** [comment]
Long since fixed.
