### ISSUE TITLE
How to specify labels ?

### ISSUE THREAD

**Issue by Kelvyn88** [jheinen/GR.jl#244]
I want to control the labels ob both axes, x , y. 

No documentations available.

**Comment by heliosdrm** [comment]
Are you looking for [xlabel](https://gr-framework.org/julia-jlgr.html#xlabel-871f49f691d93ff7beb8b0e4eeb78eb4), etc.?

(Hint for looking for documentation in the REPL: if you do `using GR` and then e.g. `? plot` you won't see much useful information, because the documented high-level functions live in the module `jlgr`, although exported from their aliases in `GR`. Try `? jlgr.plot` etc.)

**Comment by Kelvyn88** [comment]
thanks
