### ISSUE TITLE
Don't set LD_LIBRARY_PATH globally

### ISSUE THREAD

**Issue by fredrikekre** [jheinen/GR.jl#478]
Doing so breaks things for other users, for example https://github.com/JuliaDocs/Documenter.jl/issues/1965 where running `curl` breaks because it looks in Julia directories. Instead use [`addenv`](https://docs.julialang.org/en/v1/base/base/#Base.addenv) locally where you need it.

**Comment by t-bltg** [comment]
@jheinen, we don't really know the `GR` internals, but using `LD_LIBRARY_PATH` or similar on other `OS`es is really bad practices.

I don't really know how `Yggdrasil` deals with dynamic linking and relocation but it should normally be achieved through suited `rpath`s.

Could you synthesize the way `GR` works internally, so we can find another (safer) approach ?

**Comment by t-bltg** [comment]
`GKS_QT` env variable with `LD_LIBRARY_PATH` instruction set is used in [`open_socket`](https://github.com/sciapp/gr/blob/c5bd9e3ab82260267ad0c5be4a54084f7b7522e7/lib/gks/socket.c#L275), which [creates a new thread](https://github.com/sciapp/gr/blob/c5bd9e3ab82260267ad0c5be4a54084f7b7522e7/lib/gks/socket.c#L172).

So far env variables are not modified (they cannot be modified per thread since they are shared with the thread parent process)

In this thread, [a new process is created](https://github.com/sciapp/gr/blob/c5bd9e3ab82260267ad0c5be4a54084f7b7522e7/lib/gks/socket.c#L154) with the modified env variables, and afaik each process has its own set of env variables.

Thus, I do not understand how `LD_LIBRARY_PATH` can leak into the parent process and affect `curl`.

**Comment by t-bltg** [comment]
I can confirm that the `curl` warning no longer appears in `PlotDocs` after the new `GR` release.

**Comment by jheinen** [comment]
> I can confirm that the `curl` warning no longer appears in `PlotDocs` after the new `GR` release.

That's good news.
