### ISSUE TITLE
cairoplugin.dll wont load

### ISSUE THREAD

**Issue by ejmeitz** [jheinen/GR.jl#523]
Hello,

I'm using Plots.jl inside of one of my packages and when I try to save a plot with `savefig` I get this printed to the screen and then my code keeps on running.
![image](https://github.com/jheinen/GR.jl/assets/54505069/201d6536-ef7f-44ea-bbcb-0621230ce6a0)

Everything works totally fine when I use Plots outside of this package but I cannot use `savefig` inside of the package without having this error. Any help would be greatly appreciated!

Thanks

**Comment by JackDunnNZ** [comment]
I am seeing a similar problem on mac:

```
julia> Plots.savefig(plot(1:10), "test.png")
GKS: dlopen(/Users/jack/.julia/artifacts/a7c0577456fcfa84c01a589fa47ac472250e8303/lib/cairoplugin.so, 0x0001): Library not loaded: @rpath/libtiff.5.dylib
  Referenced from: <47AFD4CB-CFD9-3B15-AF23-5B5499FCD174> /Users/jack/.julia/artifacts/a7c0577456fcfa84c01a589fa47ac472250e8303/lib/cairoplugin.so
```

I believe the problem is related to https://github.com/JuliaRegistries/General/pull/86099 and https://github.com/JuliaPackaging/Yggdrasil/pull/6929, as in Libtiff_jll 4.5.1 there is no libtiff.5.dylib, only libtiff.6.dylib

Previously https://github.com/JuliaRegistries/General/pull/86099 had retroactively restricted the compat of GR_jll to avoid Libtiff_jll 4.5.x, but the new GR_jll 0.72.8 doesn't have this restriction and so pulls in the incompatible 4.5.1. It seems like the registry should be adjusted again for this new release of GR_jll?

**Comment by jheinen** [comment]
I can reproduce this problem, but I have no idea (yet) how to fix it on the GR side.

In [build_tarballs.jl](https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/GR/build_tarballs.jl), we have a compatibility requirement for `libtiff 4.3.0`.

@giordano: Do we have to switch to a newer `libtiff` version (`v4.5.1`) in GR?

**Comment by PaulSoderlind** [comment]
I get a similar error. Also, it seems as if the "Windows Security" is blocking the plot window. (No, I can't change this since this machine is admin:ed by the IT dept.)

**Comment by giordano** [comment]
https://github.com/JuliaRegistries/General/pull/87537

**Comment by giordano** [comment]
> @giordano: Do we have to switch to a newer libtiff version (v4.5.1) in GR?

For next version that'd likely be best, yes
